# Generated by Django 4.1.3 on 2022-11-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('Keyword', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
            ],
        ),
    ]
